# Generated by Django 5.2.7 on 2025-11-16 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('country', models.CharField(help_text='Kod kraju, np. PL, US, GB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='Krótki opis gatunku filmowy.')),
                ('typical_themes', models.CharField(blank=True, help_text='Typowe motywy i tematy występujące w tym gatunku.', max_length=200)),
                ('is_documentary', models.BooleanField(default=True, help_text='Czy gatunek jest dokumentalny?')),
                ('popularity_rank', models.PositiveSmallIntegerField(default=0, help_text='Ocena popularności (0–10) według oglądaczy.')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('release_year', models.PositiveSmallIntegerField(help_text='Rok premiery filmu.')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Czas trwania filmu w minutach.')),
                ('movie_format', models.CharField(choices=[('CD', 'Płyta CD'), ('W', 'Wersja cyfrowa'), ('VHS', 'Kaseta VHS')], default='W', max_length=3)),
                ('director', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalniafilmow.director')),
                ('genre', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalniafilmow.genre')),
            ],
        ),
    ]
