# Generated by Django 5.2.7 on 2025-11-18 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(help_text='Rok produkcji filmu.')),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='release_year',
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(help_text='Reżyser filmu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalniafilmow.director'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ForeignKey(help_text='Gatunek filmowy.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalniafilmow.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_format',
            field=models.CharField(choices=[('CD', 'Płyta CD'), ('W', 'Wersja cyfrowa'), ('VHS', 'Kaseta VHS')], default='W', help_text='Format filmu.', max_length=3),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(help_text='Tytuł filmu.', max_length=100),
        ),
        migrations.AddField(
            model_name='movie',
            name='production_year',
            field=models.ForeignKey(help_text='Rok produkcji filmu.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wypozyczalniafilmow.productionyear'),
        ),
    ]
