# Generated by Django 5.2.7 on 2025-11-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0002_productionyear_remove_movie_release_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('plec', models.CharField(choices=[('M', 'Mężczyzna'), ('K', 'Kobieta'), ('I', 'Inna')], default='I', help_text='Płeć klienta.', max_length=1)),
                ('rented_movie', models.OneToOneField(blank=True, help_text='Film aktualnie wypożyczony przez klienta.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renting_customer', to='wypozyczalniafilmow.movie')),
            ],
        ),
    ]
