# Generated by Django 5.2.7 on 2025-11-20 20:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0003_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='rented_movie',
        ),
        migrations.AddField(
            model_name='customer',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Data i godzina dodania klienta do systemu.'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(auto_now_add=True, help_text='Data i godzina wypożyczenia filmu.')),
                ('return_date', models.DateTimeField(blank=True, help_text='Data i godzina zwrotu filmu.', null=True)),
                ('customer', models.ForeignKey(help_text='Klient wypożyczający film.', on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmow.customer')),
                ('movie', models.ForeignKey(help_text='Wypożyczony film.', on_delete=django.db.models.deletion.CASCADE, to='wypozyczalniafilmow.movie')),
            ],
        ),
    ]
