# Generated by Django 5.2.7 on 2025-11-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0004_remove_customer_rented_movie_customer_data_dodania_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='is_documentary',
            field=models.BooleanField(default=False, help_text='Czy gatunek jest dokumentalny?'),
        ),
    ]
