# Generated by Django 5.2.7 on 2026-01-17 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0005_alter_genre_is_documentary'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_copies',
            field=models.PositiveIntegerField(default=1, help_text='Cała liczba kopii filmu w wypożyczalni.'),
        ),
    ]
