# Generated by Django 5.2.7 on 2026-01-23 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wypozyczalniafilmow', '0006_movie_number_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_format',
            field=models.CharField(choices=[('CD', 'Płyta CD'), ('BR', 'Blu-ray'), ('VHS', 'Kaseta VHS')], default='CD', help_text='Format filmu.', max_length=3),
        ),
    ]
